spring:
  application:
    name: av2-api-autenticacao
  
  # Configuração do banco de dados H2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # Configuração JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        dialect: org.hibernate.dialect.H2Dialect
  
  # Configuração H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

# Configuração do Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    health:
      show-details: always
    metrics:
      access: read-only
    prometheus:
      access: read-only
  prometheus:
    metrics:
      export:
        enabled: true

# Configuração do Springdoc OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

# Configuração do servidor
server:
  port: 8080
  servlet:
    context-path: /api

# Configuração de logging
logging:
  level:
    '[com.example.av2]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.springframework.web]': DEBUG 